== Configuration du plugin

Après téléchargement du plugin, il vous suffit juste d'activer et d'installer les dépendances openvpn (clic sur le bouton Installer/Mettre à jour)

== Configuration des équipements

Vous retrouvez ici toute la configuration de votre équipement : 

* *Nom de l'équipement Openvpn* : nom de votre équipement Openvpn,
* *Objet parent* : indique l'objet parent auquel appartient l'équipement,
* *Catégorie* : les catégories de l'équipement (il peut appartenir à plusieurs catégories),
* *Activer* : permet de rendre votre équipement actif,
* *Visible* : rend votre équipement visible sur le dashboard,

[NOTE]
Les autres options ne seront pas détaillées ici, pour avoir des informations dessus il faut vous référer à la link:https://openvpn.net/index.php/open-source/documentation.html[documention openvpn]

En-dessous vous retrouvez la liste des commandes : 

* *Nom* : le nom affiché sur le dashboard,
* *Afficher* : permet d'afficher la donnée sur le dashboard,
* *Tester* : permet de tester la commande

[NOTE]
Jeedom va vérifier toutes les 15 minutes si le VPN est bien démarré ou arreté (s'il le faut) et agir en conséquence si ce n'est pas le cas
